### ISSUE TITLE
Server Does Not Query Bungee Server Correctly

### ISSUE THREAD

**Issue by ZacharyDuBois** [FunnyItsElmo/PHP-Minecraft-Server-Status-Query#23]
Over at a project where I use this script, someone opened an issue where it always appears offline. According to the many other query status checkers, it is online and working. 

Details in DevelopGravity/Fluid-MC-Stats#20

**Comment by ZacharyDuBois** [comment]
@FunnyItsElmo any update?

**Comment by J0ker98** [comment]
I would like this too :/

**Comment by advocaite** [comment]
// Commented out because Found servers like thecharge.serverkart.com aka spigot a PVP server
                // has a totally different response, that was causing failures because of this line.
                // if($packetlength < 10) {
                //     return false;
                // }
