### ISSUE TITLE
Problems with some offline IPs

### ISSUE THREAD

**Issue by richicru** [FunnyItsElmo/PHP-Minecraft-Server-Status-Query#25]
I'm trying to get the status of the servers in my list. Most of them it takes less than a second to receive the status but some offline servers make the web keep loading till timeout. 
My host is OVH webhosting and I'm using php 5.3.
You can try to get the status with example.php of:
"mc.minley.es" <- not working (offline)
"StabilishedNetwork.com" <- working (offline)
"mc.minegodz.com" <- working (online)
Thanks for your support

**Comment by mattiabasone** [comment]
I've noticed that there's an issue with craftbukkit/spigot servers running plugins for animated MOTD
