### ISSUE TITLE
Without composer

### ISSUE THREAD

**Issue by ethernity4ever** [FunnyItsElmo/PHP-Minecraft-Server-Status-Query#37]
Can we possibly get a version without composer? I don't have access to composer on my webhost, and it would be a pain to get, so is there anyway to get this wonderful status script working without the PHP composer?

**Comment by advocaite** [comment]
to do this open up MinecraftServerQuery.php
after the use staments
include 'Packets/HandshakePacket.php';
include 'Packets/PingPacket.php';

then open up
the PingPackets.php
after namespace line add:
include 'Packet.php';

then as per the example  on readme add after namespace
include 'src/MinecraftServerStatus.php';

and it will work for you with out composer but you shoud use composer or download a skeleton composer application and just add it to vendor directory ;)

**Comment by ethernity4ever** [comment]
Thanks so much for the feedback and the reply :) I know its better to use composer, but im not in a position to use it atm, maybe after switching hosts i can :) again thank you very very much for this <3

**Comment by cm8263** [comment]
Sorry, were does the final one go?

"then as per the example on readme add after namespace
include 'src/MinecraftServerStatus.php';"

Which file?

Thanks (Sorry for Necropost :P)

**Comment by ethernity4ever** [comment]
I got no idea i stoped using this in favor of a custom one.

**Comment by FunnyItsElmo** [comment]
Check out the comment of @advocaite its the key to use this script without composer.

**Comment by cm8263** [comment]
No, I mean which file does this go in?

"then as per the example on readme add after namespace
include 'src/MinecraftServerStatus.php';"

@advocaite

**Comment by FunnyItsElmo** [comment]
Hello, 

You have to see that amazing stuff! I  couldn't believe  my  eyes, that's really not  a joke.  Just take a look  <http://thentyxiwa.cincoranchuniversityplace.com/e7cwijze>

Wishes, julian.spr

**Comment by FunnyItsElmo** [comment]
Dear! 

I've recently visited a nice  place, just take a look,  you're gonna love it for sure!  Here are some pics of  it <http://ntibundoni.asiantraditionalremedies.com/e7pzrfa>

Sincerely, julian.spr
